# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)
import numpy as np

In [0]:
# In order to ignore FutureWarning
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
iris = load_iris()
iris


{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [0]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [0]:

type(iris.target)

numpy.ndarray

In [0]:
type(iris.data)

numpy.ndarray

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
X = iris.data
Y = iris.target

In [0]:
print(X.shape, X.ndim, Y.shape, Y.ndim)

(150, 4) 2 (150,) 1


In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=7)

In [0]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 4) (38, 4) (112,) (38,)


In [0]:
# Import `StandardScaler` from `sklearn.preprocessing`
from sklearn.preprocessing import StandardScaler

# Define the scaler 
scaler = StandardScaler().fit(X_train)

# Scale the train set
X_train = scaler.transform(X_train)

# Scale the test set
X_test = scaler.transform(X_test)

In [0]:
print(X_train.ndim, X_test.ndim, y_train.ndim, y_test.ndim)

2 2 1 1


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
#encode

def encode(labels):
    print("Shape of data (BEFORE encode): %s" % str(labels.shape))
    encoded = tf.keras.utils.to_categorical(labels, num_classes = 3, dtype = "float32")
    print("Shape of data (AFTER encode): %s" % str(encoded.shape))
    return encoded

In [0]:
encoded_y_train = encode(y_train)
print(encoded_y_train)

Shape of data (BEFORE encode): (112,)
Shape of data (AFTER encode): (112, 3)
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]

In [0]:
encoded_y_test = encode(y_test)
print(encoded_y_test)

Shape of data (BEFORE encode): (38,)
Shape of data (AFTER encode): (38, 3)
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [0]:
#Initialize Sequential model
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add input layer
model.add(Dense(30, input_shape=(4,), activation='relu', name='input_layer'))

In [0]:
#Add 1st hidden layer
model.add(Dense(10, activation='relu', name='layer_1'))

In [0]:
#Add 2nd hidden layer
model.add(Dense(10, activation='relu', name='layer_2'))

In [0]:
#Add Output layer
model.add(Dense(3, activation='softmax', name='output_layer'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#Compile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 30)                150       
_________________________________________________________________
layer_1 (Dense)              (None, 10)                310       
_________________________________________________________________
layer_2 (Dense)              (None, 10)                110       
_________________________________________________________________
output_layer (Dense)         (None, 3)                 33        
Total params: 603
Trainable params: 603
Non-trainable params: 0
_________________________________________________________________
None


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
model.fit(X_train,encoded_y_train, epochs=150,validation_data=(X_test,encoded_y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/150
112/112 [==============================] - 2s 19ms/sample - loss: 1.1627 - accuracy: 0.3125 - val_loss: 1.1420 - val_accuracy: 0.3684
Epoch 2/150
112/112 [==============================] - 0s 215us/sample - loss: 1.1412 - accuracy: 0.3036 - val_loss: 1.1247 - val_accuracy: 0.3947
Epoch 3/150
112/112 [==============================] - 0s 213us/sample - loss: 1.1225 - accuracy: 0.2857 - val_loss: 1.1086 - val_accuracy: 0.3684
Epoch 4/150
112/112 [==============================] - 0s 245us/sample - loss: 1.1051 - accuracy: 0.2857 - val_loss: 1.0941 - val_accuracy: 0.3421
Epoch 5/150
112/112 [==============================] - 0s 248us/sample - loss: 1.0888 - accuracy: 0.3036 - val_loss: 1.0804 - val_accuracy: 0.3421
Epoch 6/150
112/112 [==============================] - 0s 209us/sample - loss: 1.0734 - accuracy: 0.3661 - val_loss: 1.0681 - val_accuracy: 0.3947
Epoch 7/150
112/112 [==============================] - 0s 190us/sample - l

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_pred = np.round(model.predict(X_test))

In [0]:
y_pred_1row = model.predict(X_test[0:1])

In [0]:
y_pred_1row_round = np.round(y_pred_1row)

In [0]:
print(" The Label prediction on one row is :", y_pred_1row_round)

 The Label prediction on one row is : [[0. 0. 1.]]


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
results = model.evaluate(X_test, encoded_y_test)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

38/38 [==============================] - 0s 201us/sample - loss: 0.4297 - accuracy: 0.8158
Final test set loss: 0.429712
Final test set accuracy: 0.815789




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [0]:
import pandas as pd
import numpy as np

In [0]:
sp_df=pd.read_csv('prices.csv')

In [0]:
sp_df

date symbol  ...        high     volume
0       2016-01-05 00:00:00   WLTW  ...  126.250000  2163600.0
1       2016-01-06 00:00:00   WLTW  ...  125.540001  2386400.0
2       2016-01-07 00:00:00   WLTW  ...  119.739998  2489500.0
3       2016-01-08 00:00:00   WLTW  ...  117.440002  2006300.0
4       2016-01-11 00:00:00   WLTW  ...  117.330002  1408600.0
...                     ...    ...  ...         ...        ...
851259           2016-12-30    ZBH  ...  103.930000   973800.0
851260           2016-12-30   ZION  ...   43.310001  1938100.0
851261           2016-12-30    ZTS  ...   53.740002  1701200.0
851262  2016-12-30 00:00:00    AIV  ...   45.590000  1380900.0
851263  2016-12-30 00:00:00    FTV  ...   54.480000   705100.0

[851264 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
# Dropping date and symbol columns
df = sp_df.drop(['date',"symbol"], axis=1)
df.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
data=df.head(1000)

In [0]:
data.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
data.columns

Index(['open', 'close', 'low', 'high', 'volume'], dtype='object')

In [0]:
X = data.drop(['volume'], axis=1) 

In [0]:
y = data['volume']

In [0]:
y[0:10]

0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
5    1098000.0
6     949600.0
7     785300.0
8    1093700.0
9    1523500.0
Name: volume, dtype: float64

In [0]:
y_sc= y/1000000

In [0]:
y_sc[0:10]

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
5    1.0980
6    0.9496
7    0.7853
8    1.0937
9    1.5235
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X_np =  X.to_numpy()
y_np =  y_sc.to_numpy()

In [0]:
print(X_np.dtype, y_np.dtype)

float64 float64


In [0]:
X_np = np.float32(X_np)
y_np =   np.float32(y_np)

In [0]:
print(X_np.dtype, y_np.dtype)

float32 float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X_np.ndim

2

In [0]:
X_nrm = tf.math.l2_normalize(X_np, axis=None, epsilon=1e-12, name=None)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
#number of features
n_features = X_nrm.shape[1]
X_nrm.shape

TensorShape([1000, 4])

In [0]:
#Initializing weight and bias to zeros (Cold Start)
W = tf.Variable(tf.zeros(shape=[4,1]))
b =  tf.Variable(tf.zeros(shape=(1)))

In [0]:
print(W)


<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>


In [0]:
print(b)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(features, W, b):
  y_pred = tf.add(tf.matmul(features,W),b)
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual,y_predicted):
  diff = y_actual - y_predicted
  sqr = tf.square(diff)
  avg = tf.reduce_mean(sqr)
  return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [0]:
for i in range(100):
  W,b = train(X_nrm,y_np,W,b)
  print('Current Training loss on iteration',i,loss(y_np,prediction(X_nrm,W,b)))

Current Training loss on iteration 0 tf.Tensor(236.16774, shape=(), dtype=float32)
Current Training loss on iteration 1 tf.Tensor(235.09312, shape=(), dtype=float32)
Current Training loss on iteration 2 tf.Tensor(234.06105, shape=(), dtype=float32)
Current Training loss on iteration 3 tf.Tensor(233.06989, shape=(), dtype=float32)
Current Training loss on iteration 4 tf.Tensor(232.11801, shape=(), dtype=float32)
Current Training loss on iteration 5 tf.Tensor(231.20384, shape=(), dtype=float32)
Current Training loss on iteration 6 tf.Tensor(230.32588, shape=(), dtype=float32)
Current Training loss on iteration 7 tf.Tensor(229.48273, shape=(), dtype=float32)
Current Training loss on iteration 8 tf.Tensor(228.67294, shape=(), dtype=float32)
Current Training loss on iteration 9 tf.Tensor(227.89528, shape=(), dtype=float32)
Current Training loss on iteration 10 tf.Tensor(227.14842, shape=(), dtype=float32)
Current Training loss on iteration 11 tf.Tensor(226.43115, shape=(), dtype=float32)
Cu

### Observe values of Weight
- Print the updated values

In [0]:
print(f'Updates Weight (W) values are: \n{W.numpy()}')

Updates Weight (W) values are: 
[[0.0547828 ]
 [0.0548819 ]
 [0.05422734]
 [0.05533116]]


### Observe values of Bias
- Print the updated values

In [0]:
print(f'Updates Bias(b) value is: \n{b.numpy()}')

Updates Bias(b) value is: 
[4.607657]
