# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [3]:
from scipy import stats 
import numpy as np
from scipy import stats ## this function is for SCIPY Stats which includes T test

In [4]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [6]:
from scipy.stats import ttest_1samp ## importing TTest sample lib from scipy
t_statistic, p_value = ttest_1samp(GPU1,0) ## Standerdising the Test Stats
print(t_statistic, p_value) ## if p_value < 0.05, null hypothesis will be rejected 

34.056241516158195 7.228892044970457e-15


In [8]:
print("Since P_Value < 0.05 null hypothesis is rejected")

Since P_Value < 0.05 null hypothesis is rejected


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [9]:
from scipy.stats import ttest_ind
t_statistic, p_value = ttest_ind(GPU1,GPU2) ## 2 sample testing for 2 datasets
print(t_statistic, p_value)

-2.627629513471839 0.013794282041452725


In [10]:
print("Since P_Value < 0.05 null hypothesis is rejected")

Since P_Value < 0.05 null hypothesis is rejected


## Question 3

He is trying a third GPU - GPU3.

In [11]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [12]:
#Null Hypothesis : There will be difference between speeds of GPUs,GPU1 and GPU3.
#Alternate Hypothesis : There will not be any difference.

In [13]:
t_statistic, p_value = ttest_ind(GPU1,GPU3)
print(t_statistic, p_value)

-1.4988943759093303 0.14509210993138993


In [14]:
print("Since P_Value > 0.05 null hypothesis is Accepted")

Since P_Value > 0.05 null hypothesis is Accepted


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [15]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [16]:
from scipy.stats import levene

In [17]:
levene(e1,e2,e3)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

In [18]:
print("Since p_value > 0.05, all input samples are from populations with equal variances")###3 input varience proved to be with equal varience 

Since p_value > 0.05, all input samples are from populations with equal variances


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [20]:
import scipy.stats as stats
stats.f_oneway(e1,e2,e3)

Since p_value > 0.05, two or more groups have the same population mean


In [21]:
print("Since p_value > 0.05, two or more groups have the same population mean")

Since p_value > 0.05, two or more groups have the same population mean


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

Type1 error : Rejection of a true null hypothesis.
Type2 error : Acceptance of a false null hypothesis.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


Null hypothesis : Population mean has not changed from it's previous value of 4.5 minutes.
Alternative hypothesis : Population mean is not 4.5 minutes.

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [24]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [25]:
from scipy.stats import chisquare,chi2_contingency

In [26]:
chi2_stat,p_value,degree_of_freedom,contingency = chi2_contingency(dice)
print("chi2_stat %3.5f p_value %1.6f degree_of_freedom %d" %(chi2_stat,p_value,degree_of_freedom))

chi2_stat 23.31567 p_value 0.077664 degree_of_freedom 15


In [27]:
print("contingency",contingency)

contingency [[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


In [28]:
print("Since P_Value > 0.05 null hypothesis is Accepted")

Since P_Value > 0.05 null hypothesis is Accepted


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [29]:
#Getting zscore on the above dice data using stats.zscore module
stats.zscore(dice)

array([[-0.46291005, -0.18884739, -1.83711731,  1.44115338],
       [ 1.38873015, -0.64208114,  1.22474487,  0.        ],
       [ 0.9258201 ,  0.7176201 ,  0.61237244, -1.44115338],
       [-0.9258201 ,  1.62408759,  0.61237244, -0.96076892],
       [-1.38873015,  0.03776948,  0.        ,  0.        ],
       [ 0.46291005, -1.54854863, -0.61237244,  0.96076892]])

In [30]:
#Convert zscore values to p-value
p_values = stats.norm.sf(abs(stats.zscore(dice)))
print(p_values)

[[0.32171442 0.42510621 0.03309629 0.07477068]
 [0.08245741 0.26041025 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.07477068]
 [0.17726974 0.05217856 0.27014569 0.16833418]
 [0.08245741 0.48493574 0.5        0.5       ]
 [0.32171442 0.06074513 0.27014569 0.16833418]]


In [31]:
#Mean Calculation
print("Mean",np.mean(p_values))

Mean 0.23428473233691496


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [34]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [35]:
before

array([115.52007333, 142.44180361, 137.18148049,  56.81922202,
        88.71420097,  69.48439783,  93.51149493,  25.26321978,
        65.95741269,  80.81502304, 124.99255576, 124.37960842,
        78.04425131, 109.82916133,  78.11246085, 143.71833101,
       104.25553785, 117.16178566,  99.43759728, 130.20805395,
        75.05522559, 152.82657427, 106.22314504, 108.98002469,
        81.80752361, 140.8555497 , 131.11985572, 113.31972896,
        61.46200107,  98.42878266,  66.58068504, 138.55193428,
        96.70074472,  78.99396443, 109.03615148,  60.60986474,
       102.21589184, 111.02696354, 136.21986672, 116.26181189,
        49.757882  , 141.7921108 , 117.67008835, 113.26737656,
        43.62552914, 170.42550315, 139.39790368, 164.13270025,
        94.17360425, 127.6423174 , 134.66650182,  96.97354704,
        91.88588112, 130.32516997,  56.59340381,  72.30121378,
        62.89349473,  87.4372032 ,  48.74495717,  92.92526283,
       102.1206634 ,  64.02351409,  85.51624591,  74.55

In [38]:
after

array([121.19591143, 136.43696621, 130.56426547,  52.70525238,
        81.48106121,  67.91989866,  98.22413661,  26.27467729,
        61.83421014,  80.07678391, 131.15362585, 119.89699519,
        69.92251044, 105.83104416,  76.99505882, 142.59569125,
        98.54921711, 119.1011097 , 102.75780258, 130.292522  ,
        75.83093136, 153.47407418, 104.44809913, 109.91334856,
        79.76195138, 144.51385839, 132.02381237, 105.12717698,
        58.17404672,  98.85847777,  73.58818664, 135.05038711,
        82.09539733,  76.49620856, 109.33056025,  61.37230251,
        95.06633822, 110.94659529, 137.64479931, 107.63916245,
        56.27502028, 140.77422348, 125.51395626, 106.78831416,
        44.70998166, 166.27592916, 137.77822163, 160.9120514 ,
        93.66283908, 126.76810448, 123.31456548, 101.30670201,
        88.85251122, 126.63223349,  43.24717828,  79.29250331,
        66.24863018,  90.91073385,  47.08458747,  91.99020536,
       103.12926915,  54.95495744,  80.99110519,  72.43

In [39]:
#Conducting a paired t-test
#Assuming alpha = 0.05
#Null hypothesis = Weight-loss drug works
t_statistic,p_value = stats.ttest_rel(before,after)
print(t_statistic,p_value)
print("Since p_value < 0.05,null hypothesis is rejected")

3.431294834371838 0.0006505726480806091
Since p_value < 0.05,null hypothesis is rejected
