 Statistical NLP 



In [0]:

import numpy as np # linear algebra
import pandas as pd 
import zipfile


In [0]:
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
# 1.Loading the dataset
bl_df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Project 8 res/blogtext.csv')

In [0]:
bl_df=bl_df[:4500]
bl_df.head(10)

id  ...                                               text
0  2059027  ...             Info has been found (+/- 100 pages,...
1  2059027  ...             These are the team members:   Drewe...
2  2059027  ...             In het kader van kernfusie op aarde...
3  2059027  ...                   testing!!!  testing!!!          
4  3581210  ...               Thanks to Yahoo!'s Toolbar I can ...
5  3581210  ...               I had an interesting conversation...
6  3581210  ...               Somehow Coca-Cola has a way of su...
7  3581210  ...               If anything, Korea is a country o...
8  3581210  ...               Take a read of this news article ...
9  3581210  ...               I surf the English news sites a l...

[10 rows x 7 columns]

In [0]:
print(bl_df.shape)


(4500, 7)


In [0]:
bl_df.dtypes

id         int64
gender    object
age        int64
topic     object
sign      object
date      object
text      object
dtype: object

2.Preprocess rows of the “text” column

In [0]:
## Importing countvectorizer and performing the Lowercase,
## stopwords have been forced. Unwanted spaces and characters are automatically removed unless 
## included using token_pattern 

from sklearn.feature_extraction.text import CountVectorizer
cvect = CountVectorizer(stop_words='english',lowercase=True)

In [0]:
bl_df.dtypes

id         int64
gender    object
age        int64
topic     object
sign      object
date      object
text      object
dtype: object

#### As we want to make this into a multi-label classification now we will add id	gender	age	topic	sign together to form one more table called lable so that we can consider only 2 columns

In [0]:
bl_df['labels']=bl_df['gender']+bl_df['age'].astype(str)+bl_df['topic']+bl_df['sign']
bl_df.head(8)

id  ...                           labels
0  2059027  ...                 male15StudentLeo
1  2059027  ...                 male15StudentLeo
2  2059027  ...                 male15StudentLeo
3  2059027  ...                 male15StudentLeo
4  3581210  ...  male33InvestmentBankingAquarius
5  3581210  ...  male33InvestmentBankingAquarius
6  3581210  ...  male33InvestmentBankingAquarius
7  3581210  ...  male33InvestmentBankingAquarius

[8 rows x 8 columns]

## drop id	gender	age	topic	sign and date so that we will have only 2 colums for consideration  

In [0]:
bl_df1=bl_df.drop(['id','gender','age','topic','sign','date'],axis=1)
print(bl_df1.head(5))

                                                text                           labels
0             Info has been found (+/- 100 pages,...                 male15StudentLeo
1             These are the team members:   Drewe...                 male15StudentLeo
2             In het kader van kernfusie op aarde...                 male15StudentLeo
3                   testing!!!  testing!!!                           male15StudentLeo
4               Thanks to Yahoo!'s Toolbar I can ...  male33InvestmentBankingAquarius


Separating test and lables as x and y so that we can split and train the data 

In [0]:
x=bl_df1['text']
y=bl_df1['labels']
print(x.head(5))
print(y.head(5))

0               Info has been found (+/- 100 pages,...
1               These are the team members:   Drewe...
2               In het kader van kernfusie op aarde...
3                     testing!!!  testing!!!          
4                 Thanks to Yahoo!'s Toolbar I can ...
Name: text, dtype: object
0                   male15StudentLeo
1                   male15StudentLeo
2                   male15StudentLeo
3                   male15StudentLeo
4    male33InvestmentBankingAquarius
Name: labels, dtype: object


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# split X and y into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=10)

In [0]:
##Training data
print(x_train.shape)
print(y_train.shape)

(3375,)
(3375,)


In [0]:
#Test data
print(x_test.shape)
print(y_test.shape)

(1125,)
(1125,)


5.Feeding input data into CountVectorizer after including ngram using Use ngram_range=(1, 2) 

In [0]:
cvect = CountVectorizer(stop_words='english',lowercase=True,ngram_range=(1,2))
cvect.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

vocablury Size 

In [0]:
len(cvect.vocabulary_)

225157

# Convert Training/Test data Count Vectors

In [0]:
x_train_ct=cvect.transform(x_train)
x_test_ct=cvect.transform(x_test)

In [0]:
print(x_train_ct.shape)
print(x_test_ct.shape)

(3375, 225157)
(1125, 225157)


In [0]:
#sparse matrix
print(x_train_ct[0])

  (0, 53953)	1
  (0, 53954)	1
  (0, 54482)	1
  (0, 54601)	1
  (0, 57113)	1
  (0, 57118)	1
  (0, 58287)	1
  (0, 58322)	1
  (0, 79165)	2
  (0, 79687)	1
  (0, 79731)	1
  (0, 89639)	1
  (0, 89710)	1
  (0, 114366)	1
  (0, 114367)	1
  (0, 115680)	1
  (0, 115700)	1
  (0, 118609)	1
  (0, 120512)	1
  (0, 120616)	1
  (0, 121070)	1
  (0, 121151)	1
  (0, 169275)	1
  (0, 169329)	1
  (0, 180323)	1
  (0, 180326)	1
  (0, 182005)	1
  (0, 182078)	1
  (0, 202824)	1
  (0, 202864)	1
  (0, 221987)	1
  (0, 222047)	1


printing the counts in y_train

In [0]:
y_train.value_counts()

male35TechnologyAries         1712
female34indUnkSagittarius      292
female24indUnkScorpio          144
male24EngineeringLibra          96
female15StudentLibra            91
                              ... 
female23indUnkAquarius           1
male26Museums-LibrariesLeo       1
female26AccountingAquarius       1
female25indUnkCapricorn          1
female36StudentGemini            1
Name: labels, Length: 74, dtype: int64

In [0]:
A=y_train.value_counts().to_dict()
A

{'female14indUnkAquarius': 5,
 'female14indUnkAries': 17,
 'female14indUnkCancer': 2,
 'female14indUnkLeo': 4,
 'female15StudentAquarius': 50,
 'female15StudentCancer': 7,
 'female15StudentGemini': 5,
 'female15StudentLeo': 10,
 'female15StudentLibra': 91,
 'female15indUnkAries': 21,
 'female16indUnkLeo': 15,
 'female16indUnkSagittarius': 1,
 'female16indUnkTaurus': 16,
 'female17StudentAries': 17,
 'female17StudentGemini': 8,
 'female17StudentLeo': 28,
 'female17StudentScorpio': 4,
 'female23StudentTaurus': 15,
 'female23indUnkAquarius': 1,
 'female23indUnkAries': 7,
 'female23indUnkLibra': 16,
 'female23indUnkSagittarius': 3,
 'female23indUnkVirgo': 2,
 'female24BankingLibra': 3,
 'female24indUnkAries': 10,
 'female24indUnkScorpio': 144,
 'female25BusinessServicesAries': 18,
 'female25StudentTaurus': 21,
 'female25indUnkCapricorn': 1,
 'female25indUnkLibra': 17,
 'female25indUnkTaurus': 5,
 'female26AccountingAquarius': 1,
 'female26ScienceSagittarius': 3,
 'female27EducationAquarius

In [0]:
A['female15StudentLibra']

91

In [0]:
A['male15ScienceLibra']

19

7.Multi lable transformation 

In [0]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

In [0]:
y_train1=mlb.fit_transform(y_train)
y_train1

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [0]:
y_test1=mlb.fit_transform(y_test)
y_test1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0]])

8.using OneVsRestClassifier and LogisticRegression

In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(solver='lbfgs',max_iter=1000)
clf=OneVsRestClassifier (clf)

In [0]:
clf.fit(x_train_ct, y_train1)


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 24 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 28 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 34 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 35 is present in all training examples.
  str(classes[c]))


OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=1000,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

9.i. Accuracy score 
ii. F1 score 
iii. Average precision score 
iv. Average recall score 

In [0]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.metrics import f1_score,classification_report, confusion_matrix,accuracy_score

In [0]:
y_predict = clf.predict(x_test_ct)
print(y_predict)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [0]:
y_predict1=mlb.inverse_transform(y_predict)
print(metrics.accuracy_score(y_test1, y_predict))

0.5653333333333334


In [0]:
print(metrics.classification_report(y_test1, y_predict))

              precision    recall  f1-score   support

           0       0.82      0.36      0.50        39
           1       0.85      0.48      0.61       182
           2       0.74      0.42      0.54       185
           3       0.85      0.96      0.90       776
           4       0.82      0.55      0.66       228
           5       0.85      0.92      0.88       731
           6       0.50      0.07      0.12        28
           7       0.90      0.36      0.52        74
           8       0.50      0.05      0.09        20
           9       0.84      0.93      0.88       688
          10       0.79      0.35      0.49        31
          11       0.84      0.32      0.46        50
          12       0.69      0.20      0.31        55
          13       0.00      0.00      0.00         9
          14       0.90      0.41      0.56        22
          15       0.77      0.44      0.56       137
          16       1.00      0.08      0.15        12
          17       0.00    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


True lable and pridicted lable 5 examples 

In [0]:
y_predict_in = mlb.inverse_transform(y_predict)
y_test1_in = mlb.inverse_transform(y_test1)

In [0]:
print("predicted :",y_predict_in[0])
print("Actual :",y_test1_in[0])

predicted : ('4', 'S', 'U', 'a', 'd', 'e', 'f', 'i', 'k', 'l', 'm', 'n', 'r', 's', 't', 'u')
Actual : ('3', '4', 'S', 'U', 'a', 'd', 'e', 'f', 'g', 'i', 'k', 'l', 'm', 'n', 'r', 's', 't', 'u')


In [0]:
print("predicted :",y_predict_in[32])
print("Actual :",y_test1_in[32])


predicted : ('3', '5', 'A', 'T', 'a', 'c', 'e', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'r', 's', 'y')
Actual : ('1', '7', 'S', 'a', 'c', 'd', 'e', 'f', 'i', 'l', 'm', 'n', 'o', 'p', 'r', 't', 'u')


In [0]:
print("predicted :",y_predict_in[45])
print("Actual :",y_test1_in[45])


predicted : ('3', '5', 'A', 'T', 'a', 'c', 'e', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'r', 's', 'y')
Actual : ('1', '7', 'G', 'S', 'a', 'd', 'e', 'f', 'i', 'l', 'm', 'n', 't', 'u')


In [0]:
print("predicted :",y_predict_in[56])
print("Actual :",y_test1_in[56])

predicted : ('3', '4', 'S', 'U', 'a', 'd', 'e', 'f', 'g', 'i', 'k', 'l', 'm', 'n', 'o', 'r', 's', 't', 'u')
Actual : ('3', '4', 'S', 'U', 'a', 'd', 'e', 'f', 'g', 'i', 'k', 'l', 'm', 'n', 'r', 's', 't', 'u')


In [0]:
print("predicted :",y_predict_in[230])
print("Actual :",y_test1_in[230])

predicted : ('3', '4', 'U', 'a', 'd', 'e', 'f', 'g', 'i', 'k', 'l', 'm', 'n', 'r', 's', 't', 'u')
Actual : ('3', 'A', 'B', 'I', 'a', 'e', 'g', 'i', 'k', 'l', 'm', 'n', 'q', 'r', 's', 't', 'u', 'v')
